name: bts2

channels:
  - conda-forge
  - dglteam/label/th21_cu118
  - openeye
  - pytorch
  - nvidia

dependencies:
  - python=3.12
  - pip
  - pytorch-cuda=11.8.0
  - cuda-version=11.8

  # General
  - openmm=8.2.0
  - openmmtools
  - loguru
  - tqdm
  - seaborn
  - dask
  - dask-jobqueue
  - matplotlib
  - numpy
  - threadpoolctl
  - scikit-learn

  # Dataset handling
  #  - h5py # This should install anyway, but including it causes the env solve to hang
  #- datasets

  # Parameterization
  #- openff-toolkit >=0.17.0
  #- openff-interchange >=0.3.17
  #- openff-nagl-models >=2025.9.0
  - openff-toolkit
  - openff-nagl
  - openff-interchange
  - openeye-toolkits
  - openff-units
  - rdkit
  - periodictable

  # Training
  - pyarrow
  - tensorboard
  - tensorboardX
  - tbparse
  - torchdata<=0.10.0
  - pytorch=2.4.1
  - torchaudio=2.4.1
  - torchvision=0.19.1

  # Benchmarking
  - openff-qcsubmit
  - geometric

  # Dev
  - pre-commit
  - ruff
  - mypy

  # Include for dependencies
  - smee
  - descent

# Pip
  - pip:
      # This fork adds support for linear bonds and angles to Smee
      - git+https://github.com/thomasjamespope/smee.git
      - git+https://github.com/openforcefield/yammbs.git
      - deepchem
      - more_itertools
